'use client';

import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import UnifiedHero from '@/components/layout/UnifiedHero';
import FormSuccess from '@/components/forms/FormSuccess';

type Review = { id: number | string; name: string; tripType: string; review: string; rating: number };
const featured: Review[] = [
  { id:'f1', name:'Amelia R.', tripType:'Uganda Gorilla Trek', review:'Every detail was handled with care. The gorilla tracking experience felt personal, well-organized, and deeply meaningful.', rating:5 },
  { id:'f2', name:'David K.', tripType:'Kenya Safari Escape', review:'The wildlife was extraordinary, but the professionalism of the guides made the experience stand out.', rating:5 },
  { id:'f3', name:'Sofia M.', tripType:'Rwanda Conservation Tour', review:'WildMed balanced adventure and purpose brilliantly. We saw incredible wildlife and learned how conservation changes lives.', rating:5 },
  { id:'f4', name:'Noah T.', tripType:'Tanzania Adventure', review:'From the first briefing to the final game drive, the experience was smooth, thoughtful, and unforgettable.', rating:5 },
  { id:'f5', name:'Priya N.', tripType:'Custom Expedition', review:'The team created a custom itinerary that matched our interests perfectly. It felt curated, not generic.', rating:5 },
  { id:'f6', name:'Martin C.', tripType:'Medical Field Program', review:'A powerful mix of learning, service, and hands-on fieldwork. It was structured, inspiring, and impactful.', rating:5 },
];

export default function ReviewPage() {
  const [reviews,setReviews]=useState<Review[]>([]), [loading,setLoading]=useState(true), [submitting,setSubmitting]=useState(false), [submitted,setSubmitted]=useState(false);
  const [error,setError]=useState(''), [rating,setRating]=useState(5);
  useEffect(()=>{ fetch('/api/reviews',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setReviews(d.reviews)}).catch(console.error).finally(()=>setLoading(false)); },[]);
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSubmitting(true);setError('');const form=event.currentTarget,data=new FormData(form);try{const response=await fetch('/api/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:data.get('name'),tripType:data.get('tripType'),review:data.get('review'),rating})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to publish review.');setReviews(current=>[result.review,...current]);form.reset();setRating(5);setSubmitted(true)}catch(err){setError(err instanceof Error?err.message:'Unable to publish review.')}finally{setSubmitting(false)}};
  return <main className="overflow-hidden bg-slate-950 text-white">
    <UnifiedHero eyebrow="Real journeys · Real perspectives" title={<>Stories from <span className="block italic text-sunset-gold">the field.</span></>} description="Hear from travelers, students, and professionals whose East African experiences became stories worth bringing home." backgroundImage="/assets/heroes/traveler-reviews-hero.png" mainImage="/assets/heroes/traveler-reviews-hero.png" secondaryImage="/assets/uganda-rwanda-11day/day7-lake-bunyonyi.png" imageAlt="Travelers with a WildMed safari guide" trustText="Real traveler perspectives" note="Memories worth sharing" stats={[{value:'98%',label:'Traveler satisfaction',icon:'ri-emotion-happy-line'},{value:'4.9/5',label:'Average rating',icon:'ri-star-line'},{value:'500+',label:'Trips delivered',icon:'ri-suitcase-3-line'},{value:'72%',label:'Repeat travelers',icon:'ri-repeat-line'}]} actions={<><a href="#traveler-stories" className="rounded-2xl bg-sunset-gold px-8 py-4 text-center font-black text-slate-950">Read their stories</a><Link href="/Custom-Safaris" className="rounded-2xl border border-sunset-gold/70 px-8 py-4 text-center font-black">Plan your journey</Link></>} />
    <section id="traveler-stories" className="relative px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-6xl"><div className="mb-14 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.3em] text-sunset-gold">Traveler stories</p><h1 className="headline mt-3 text-4xl font-bold sm:text-6xl">Pinned to the corkboard</h1></div><p className="max-w-sm border-l-2 border-sunset-gold pl-4 text-slate-400">Field notes travelers have sent back from East Africa.</p></div>{loading&&<p className="mb-7 text-sm text-slate-500">Loading recent reviews…</p>}<div className="grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{[...reviews,...featured].map((item,index)=><article key={item.id} className={`group relative mt-2 bg-[#fff7e8] px-6 pb-7 pt-8 text-slate-800 shadow-xl transition hover:-translate-y-2 ${index%3===0?'md:-rotate-1':index%3===1?'md:rotate-1':'md:-rotate-2'}`}><span className="absolute -top-3 left-1/2 h-5 w-5 -translate-x-1/2 rounded-full bg-sunset-gold shadow"/><div className="mb-4 flex justify-between gap-3"><div><h2 className="headline text-xl font-bold text-slate-900">{item.name}</h2><span className="mt-1 inline-block rounded-full border border-sunset-orange/40 px-2 py-0.5 text-[11px] text-orange-800">{item.tripType}</span></div><span className="text-sunset-gold" aria-label={`${item.rating} out of 5 stars`}>{'★'.repeat(item.rating)}{'☆'.repeat(5-item.rating)}</span></div><p className="leading-6 text-slate-700">“{item.review}”</p></article>)}</div></div></section>
    <section className="bg-slate-900 px-5 py-20"><div className="mx-auto max-w-6xl bg-[#fff7e8] p-8 text-slate-900 shadow-2xl sm:p-14">{submitted?<FormSuccess title="Your story is now on the corkboard" message="Your review has been saved and published for future travelers to read." onClose={()=>setSubmitted(false)} actionLabel="Write another review"/>:<><p className="text-sm font-bold text-orange-800">Add your entry</p><h2 className="headline mt-3 text-4xl font-bold sm:text-5xl">Tell us about your WildMed journey</h2><p className="mt-4 text-slate-600">Share the moments, learning, and advice you would give the next traveler.</p><form onSubmit={submit} className="mt-10 grid gap-7 md:grid-cols-2"><label className="text-sm text-slate-500">Your name<input name="name" required minLength={2} maxLength={100} className="mt-2 w-full border-b border-slate-400 bg-transparent py-2 text-slate-900 outline-none focus:border-sunset-orange"/></label><label className="text-sm text-slate-500">Trip type<select name="tripType" className="mt-2 w-full border-b border-slate-400 bg-transparent py-2 text-slate-900"><option>Uganda Gorilla Trek</option><option>Kenya Safari Escape</option><option>Tanzania Adventure</option><option>Rwanda Conservation Tour</option><option>Custom Expedition</option><option>Study Abroad</option><option>Medical Field Program</option><option>Veterinary Conservation Program</option></select></label><fieldset className="md:col-span-2"><legend className="text-sm text-slate-500">Your rating</legend><div className="mt-2 flex">{[1,2,3,4,5].map(star=><button key={star} type="button" onClick={()=>setRating(star)} className={`text-3xl ${star<=rating?'text-sunset-gold':'text-slate-300'}`} aria-label={`${star} stars`}>★</button>)}</div></fieldset><label className="text-sm text-slate-500 md:col-span-2">Your review<textarea name="review" required minLength={20} maxLength={2000} rows={5} className="mt-2 w-full resize-y border-b border-slate-400 bg-transparent py-2 text-slate-900 outline-none focus:border-sunset-orange"/></label>{error&&<p className="text-sm text-red-700 md:col-span-2">{error}</p>}<div className="flex justify-end md:col-span-2"><button disabled={submitting} className="bg-slate-950 px-8 py-4 font-black text-white disabled:opacity-60">{submitting?'Publishing…':'Publish review'}</button></div></form></>}</div></section>
  </main>;
}
