import type { ItineraryConfig, ItineraryDay, ItineraryLodge, ItinerarySegment } from "@/components/itinerary/ItineraryPage";

const s = (title: string, items: string[], icon = "ri-compass-3-line"): ItinerarySegment => ({ title, items, icon });
const d = (label: string, title: string, route: string, image: string, segments: ItinerarySegment[], noteTitle?: string, noteText?: string): ItineraryDay => ({ label, title, route, image, segments, ...(noteTitle && noteText ? { note: { title: noteTitle, text: noteText } } : {}) });
const l = (name: string, location: string, nights: string, level: string, image: string, description: string, amenities?: string[]): ItineraryLodge => ({ name, location, nights, level, image, description, amenities });
const h = (images: string[], names: string[]) => images.map((image, index) => ({ image, title: names[index] || `Journey highlight ${index + 1}`, category: index % 3 === 0 ? "Wildlife" : index % 3 === 1 ? "Landscape" : "Culture", text: `A defining moment from ${names[index] || "this WildMed journey"}.` }));

const standardFeatures = [
  { icon: "ri-user-star-line", title: "Private tour", text: "A guided journey arranged around your group" },
  { icon: "ri-calendar-event-line", title: "Flexible dates", text: "Choose a start date that suits your plans" },
  { icon: "ri-route-line", title: "Customizable", text: "Adjust the experience with our trip planners" },
  { icon: "ri-user-heart-line", title: "Solo traveller friendly", text: "Personal support for individual adventurers" },
];

const standardPreparation = [
  { title: "Required documentation", icon: "ri-file-list-3-line", groups: [
    { title: "Essential documents", items: ["Valid passport with 6+ months remaining", "Uganda visa (available on arrival, USD $50)", "Yellow fever vaccination certificate", "Travel insurance with medical evacuation", "Trekking permit confirmation supplied by WildMed"] },
    { title: "Medical requirements", items: ["Consult your doctor before travel", "Recommended vaccinations up to date", "Carry personal medication", "Malaria prevention recommended", "Comprehensive travel insurance required"] },
  ]},
  { title: "Gorilla trekking packing list", icon: "ri-luggage-cart-line", groups: [
    { title: "Trekking gear", items: ["Waterproof hiking boots, broken in", "Garden gloves for vegetation", "Lightweight rain jacket or poncho", "Small waterproof daypack", "Walking sticks provided where required"] },
    { title: "Clothing", items: ["Long-sleeved shirts in neutral colours", "Long quick-dry trousers", "Warm fleece or jacket", "Brimmed hat", "Extra wool socks"] },
    { title: "Essential items", items: ["High-SPF sunscreen", "DEET-based insect repellent", "Camera with spare batteries", "Personal medication", "Small first-aid kit"] },
  ]},
  { title: "Fitness & gorilla trekking rules", icon: "ri-heart-pulse-line", groups: [
    { title: "Physical preparation", items: ["Moderate fitness level recommended", "Treks may last 2-8 hours", "Expect uneven and muddy terrain", "Prepare for humid forest conditions", "Porters are available locally"] },
    { title: "Gorilla trekking rules", items: ["Maximum 8 visitors per gorilla group", "Keep the required distance from gorillas", "No flash photography", "Keep voices low", "Do not trek when unwell", "Follow ranger instructions at all times"] },
  ]},
];

const standardExcluded = ["International flights", "Visa fees", "Travel and medical insurance", "Alcoholic and premium beverages", "Personal shopping and souvenirs", "Tips for guides and lodge staff", "Optional activities not mentioned", "Personal expenses"];
const standardBenefits = ["Fast availability confirmation", "Flexible payment options", "Airport transfer coordination", "Personal trip-planning consultation"];
const standardNotes = ["Price is based on double occupancy", "Permits are non-refundable once confirmed", "A deposit is required to secure permits and accommodation", "Balance is due before travel", "Prices may change with season, availability and exchange rates"];
const permitNote = "Primate permits are limited and should be secured well in advance. Gorilla trekking has a minimum age requirement of 15 years.";

export const uganda4Day: ItineraryConfig = {
  title: "4-Day Uganda Express Safari",
  shortTitle: "4-Day Uganda Express Safari",
  eyebrow: "Two primate encounters · One express journey",
  description: "Experience chimpanzees in Kibale and mountain gorillas in Bwindi in just four days, travelling from Kigali through Uganda's forest landscapes.",
  heroImage: "/assets/4day-express/express1.png", duration: "4 days", nights: "3 nights", destination: "Uganda", travelStyle: "Shared group", price: "$2,840 USD",
  days: [
    d("01","Kigali to Kibale Forest","Kigali to Uganda","/assets/4day-express/express1.png",[s("Morning journey",["Pickup from Kigali hotel/airport","Cross border into Uganda","Scenic drive to Kibale Forest","Arrive at Kibale Forest National Park"],"ri-car-line"),s("Afternoon experience",["Chimpanzee tracking session","See other primates in the forest","Check into Kibale Forest Lodge","Dinner at own expense at lodge"],"ri-bear-smile-line")],"Safari insight","Kibale Forest is known as Africa's premier chimpanzee tracking destination, with over 1,500 chimpanzees and 12 other primate species."),
    d("02","Journey to Bwindi Forest","Kibale to Bwindi","/assets/4day-express/express2.png",[s("Travel day",["Breakfast at the lodge","Scenic drive to Bwindi Forest","Views of Ugandan countryside","Lunch en route at a local restaurant"],"ri-road-map-line"),s("Evening preparation",["Arrive at Rushaga Gorilla Haven's Lodge","Briefing about gorilla trekking","Prepare gear for tomorrow's trek","Dinner and rest at the lodge"],"ri-hotel-line")],"Expert guidance","Bwindi Impenetrable Forest is home to nearly half of the world's remaining mountain gorillas—about 459 individuals in 36 families."),
    d("03","Gorilla Trekking Experience","Bwindi Impenetrable Forest","/assets/4day-express/express3.png",[s("Gorilla trekking",["Early breakfast at the lodge","Transfer to park headquarters","Morning briefing by park rangers","Trek to find a mountain gorilla family","One hour with the gentle giants"],"ri-footprint-line"),s("Afternoon & reflection",["Return to the lodge for lunch","Rest and relaxation time","Review photos and memories","Optional village community visit"],"ri-camera-line")],"Trekking essentials","Trekking can take 2-8 hours depending on the gorillas' location. Good fitness is required, the minimum age is 15, and ranger instructions must be followed."),
    d("04","Return to Kigali","Bwindi to Kigali","/assets/4day-express/express4.png",[s("Morning departure",["Breakfast at the lodge","Pack and prepare for departure","Scenic drive back to Rwanda","Cross the border into Rwanda"],"ri-sun-line"),s("Arrival in Kigali",["Lunch en route at a local restaurant","Views of Rwanda's rolling hills","Drop-off at Kigali hotel/airport","End of the safari"],"ri-plane-line")],"Departure notes","Schedule flights from Kigali for evening, after 5pm. We recommend an overnight in Kigali for early morning flights."),
  ],
  highlights: h([1,2,3,4,5,6,7,8].map(n=>`/assets/4day-express/express${n}.png`),["Chimpanzee tracking","Kibale rainforest","Journey south","Bwindi highlands","Mountain gorillas","Forest trails","Primate encounters","Uganda landscapes"]),
  lodges: [l("Kibale Forest Lodge","Kibale Forest","1 night","Comfort","/assets/4day-express/kibale-lodge.png","A welcoming forest base close to chimpanzee tracking trails."),l("Rushaga Gorilla Haven's Lodge","Bwindi","2 nights","Comfort","/assets/4day-express/rushaga-lodge.png","A convenient lodge near the gorilla trekking headquarters, surrounded by forested hills.")],
  features: [{icon:"ri-group-line",title:"Shared group tour",text:"Travel with a small group of 2-6 people"},{icon:"ri-wallet-3-line",title:"Budget-friendly",text:"Two major primate experiences in four days"},...standardFeatures.slice(1,4)],
  included: ["Shared safari transport","English-speaking driver-guide","Chimpanzee tracking experience","Gorilla trekking permit","Three nights' accommodation","Park entrance fees","Airport/hotel transfers","Bottled water during drives"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Base safari package","Included"],["Chimpanzee tracking","Included"],["Gorilla trekking permit","Included"],["Transport and guiding","Included"]], bookingBenefits: ["Group discounts available","Quick permit confirmation",...standardBenefits.slice(1)], pricingInclusions: ["Three nights' accommodation","Chimpanzee and gorilla tracking","Shared transport and professional guide","Park fees and transfers","Specified meals and bottled water"], importantNotes: ["Price based on a shared group of 2-6 people","Single supplement: $450",...standardNotes.slice(1)], permitNote,
};

export const uganda4DayFlyIn: ItineraryConfig = {
  title: "4-Day Fly-in Gorilla & Chimpanzee Safari", shortTitle: "4-Day Fly-in Primate Safari", eyebrow: "Ultimate primate adventure · Fly-in comfort", description: "Trade long road transfers for scenic flights, luxury forest lodges, mountain gorillas in Bwindi and chimpanzees in Kibale.", heroImage: "/assets/flyin-primate/flyin1.png", duration: "4 days", nights: "3 nights", destination: "Uganda", travelStyle: "Luxury fly-in", price: "$7,680 USD",
  days: [
    d("01","Arrival & Flight to Bwindi","Entebbe to Bwindi","/assets/flyin-primate/flyin1.png",[s("Arrival & scenic flight",["Arrive at Entebbe International Airport","Meet your personal WildMed guide","Private transfer to Entebbe Airstrip","Scenic flight to Kisoro/Kihihi Airstrip"],"ri-plane-line"),s("Luxury lodge arrival",["Check into Four Gorillas Lodge","Unwind in luxury accommodation","Prepare for tomorrow's gorilla trek","Gourmet dinner at the lodge"],"ri-hotel-line")],"Fly-in advantage","The scenic flight saves more than eight hours of driving while offering aerial views and maximizing safari time."),
    d("02","Gorilla Trekking in Bwindi","Bwindi Impenetrable Forest","/assets/flyin-primate/flyin2.png",[s("Gorilla trekking experience",["Early breakfast at the luxury lodge","Transfer to park headquarters","Safety briefing by park rangers","Trek through lush rainforest","One hour with a mountain gorilla family"],"ri-footprint-line"),s("Evening relaxation",["Return to the lodge for lunch","Rest and share trekking stories","Professional photography review","Gourmet dinner under the stars"],"ri-camera-line")],"Conservation note","Bwindi is home to almost half of the world's remaining mountain gorillas. Your permit supports conservation and local communities."),
    d("03","Fly to Kibale & Chimpanzee Trek","Bwindi to Kibale","/assets/flyin-primate/flyin3.png",[s("Morning flight & transfer",["Breakfast with mountain views","Flight to Kasese Airstrip","Scenic drive to Kibale National Park","Check into Kyaninga Lodge","Lakeside lunch experience"],"ri-plane-line"),s("Chimpanzee trekking",["Afternoon chimpanzee tracking","See wild chimpanzees in their habitat","Observe red colobus monkeys","Look for L'Hoest's monkeys","Expert guide commentary"],"ri-bear-smile-line")],"Lodge highlight","Kyaninga Lodge overlooks Lake Nyinambuga and the Rwenzori Mountains, the legendary Mountains of the Moon."),
    d("04","Lakeside Morning & Return","Kibale to Entebbe","/assets/flyin-primate/flyin4.png",[s("Morning at Kyaninga Lodge",["Sunrise over Lake Nyinambuga","Final luxury breakfast","Lakeside photography session","Optional nature walk"],"ri-sun-line"),s("Return journey",["Transfer to Kasese Airstrip","Flight back to Entebbe","Lunch en route or at the airport","Drop-off at hotel or airport"],"ri-plane-line")],"Departure planning","Schedule international flights after 6pm. Lake Victoria Serena Hotel can be arranged for an overnight stay."),
  ],
  highlights: h([1,2,3,4,5,6,7,8].map(n=>`/assets/flyin-primate/flyin${n}.png`),["Scenic flight","Bwindi gorillas","Rainforest trek","Kibale chimpanzees","Aerial landscapes","Lake Nyinambuga","Luxury lodge life","Primate country"]),
  lodges: [l("Four Gorillas Lodge","Bwindi","2 nights","Luxury","/assets/flyin-primate/four-gorillas-lodge.png","An intimate luxury forest lodge near the gorilla trekking trailhead.",["Free WiFi","Restaurant","Hot showers","Forest views","Spa"]),l("Kyaninga Lodge","Kibale","1 night","Luxury","/assets/flyin-primate/kyaninga-lodge.jpg","A striking lakeside lodge overlooking a crater lake and the Rwenzori Mountains.",["Free WiFi","Restaurant","Lake views","Pool"] )],
  features: [{icon:"ri-time-line",title:"Time efficient",text:"Scenic flights replace long road transfers"},{icon:"ri-flight-takeoff-line",title:"Aerial views",text:"See Uganda's lakes, forests and highlands from above"},{icon:"ri-hotel-line",title:"Enhanced comfort",text:"Luxury lodges and private transfers"},{icon:"ri-settings-3-line",title:"Fully customizable",text:"Tailor flights, stays and activities"}],
  included: ["Domestic scenic flights","Private airport and airstrip transfers","Luxury lodge accommodation","Gorilla trekking permit (USD 700 value)","Chimpanzee trekking permit","Professional driver-guide","Specified meals","Park entrance fees"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Luxury accommodation","Included"],["Domestic flights","Included"],["Gorilla permit","Included (USD 700 value)"],["Chimpanzee trek","Included"]], bookingBenefits: ["Early booking flight advantages","Priority permit coordination",...standardBenefits.slice(1)], pricingInclusions: ["Three nights' luxury accommodation","Domestic flights and private transfers","Gorilla and chimpanzee permits","All specified meals","Professional guides and park fees"], importantNotes: ["Price based on double occupancy","Single supplement: $1,200","Luxury upgrade options from $500",...standardNotes.slice(1)], permitNote,
};

export const uganda5DayKisoro: ItineraryConfig = {
  title: "5-Day Best of Kisoro Tour", shortTitle: "5-Day Best of Kisoro Tour", eyebrow: "Hidden treasures of Southwest Uganda", description: "Combine Mgahinga gorillas, Batwa heritage, coffee culture, golden monkeys and the calm waters of Lake Bunyonyi.", heroImage: "/assets/kisoro-tour/kisoro1.png", duration: "5 days", nights: "4 nights", destination: "Kisoro", travelStyle: "Private", price: "$3,870 USD",
  days: [
    d("01","Arrival & Transfer to Kisoro","Entebbe to Kisoro","/assets/kisoro-tour/kisoro1.png",[s("Arrival & journey",["Arrive at Entebbe International Airport","Meet your personal WildMed guide","Scenic drive through Southwest Uganda","Views of green hills and local life"],"ri-car-line"),s("Accommodation & evening",["Check into Ichumbi Hotel","Unwind after the journey","Dinner at the lodge","Briefing about the days ahead"],"ri-hotel-line")],"Travel insight","Kisoro lies near the borders of Rwanda and DRC, surrounded by volcanic mountains and Uganda's famous terraced hills."),
    d("02","Gorilla Trekking in Mgahinga","Mgahinga Gorilla National Park","/assets/kisoro-tour/kisoro2.png",[s("Gorilla trekking experience",["Early breakfast at the lodge","Transfer to Mgahinga Gorilla National Park","Briefing by park rangers","Trek to find a mountain gorilla family","One hour with the gentle giants"],"ri-footprint-line"),s("Afternoon & photography",["Return to the lodge for lunch","Rest and relaxation time","Review photos and memories","Optional evening village walk"],"ri-camera-line")],"Expert guidance","Mgahinga is one of only three parks in the world where endangered mountain gorillas can be seen."),
    d("03","Batwa Culture & Coffee Experience","Cultural immersion day","/assets/kisoro-tour/kisoro3.png",[s("Batwa cultural trail",["Visit the indigenous Batwa people","Learn about their ancient forest lifestyle","Traditional medicine demonstration","Storytelling and cultural exchange","Support community tourism"],"ri-community-line"),s("Coffee farm experience",["Visit a local coffee farm","Hands-on harvesting","Learn roasting techniques","Taste Ugandan Arabica coffee","Purchase fresh coffee beans"],"ri-cup-line")],"Cultural significance","The Batwa are the original inhabitants of these forests. This experience supports heritage preservation and sustainable livelihoods."),
    d("04","Golden Monkeys & Lake Bunyonyi","Kisoro to Lake Bunyonyi","/assets/kisoro-tour/kisoro4.png",[s("Golden monkey tracking",["Morning golden monkey tracking","See playful primates in bamboo","Photography opportunities","Learn about conservation efforts"],"ri-bear-smile-line"),s("Lake Bunyonyi transfer",["Scenic drive to Lake Bunyonyi","Check into Arcadia Lodge","Relaxing boat ride","Visit the Place of Many Birds islands"],"ri-ship-line")],"Scenic beauty","Lake Bunyonyi is Africa's second deepest lake, with 29 islands, tranquil scenery and abundant birdlife."),
    d("05","Lake Sunrise & Return to Entebbe","Lake Bunyonyi to Entebbe","/assets/kisoro-tour/kisoro5.png",[s("Morning at Lake Bunyonyi",["Sunrise views over the lake","Final lakeside breakfast","Optional morning canoe ride","Photography of misty landscapes"],"ri-sun-line"),s("Return journey",["Begin the return to Entebbe","Lunch stop en route","Scenic countryside drive","Airport or hotel drop-off"],"ri-car-line")],"Departure notes","Schedule flights after 6pm. An overnight in Entebbe is recommended for early morning flights."),
  ],
  highlights: h([1,2,3,4,5,6].map(n=>`/assets/kisoro-tour/kisoro${n}.png`),["Mgahinga gorillas","Virunga landscapes","Batwa heritage","Coffee culture","Golden monkeys","Lake Bunyonyi"]),
  lodges: [l("Ichumbi Hotel","Kisoro","3 nights","Comfort","/assets/kisoro-tour/ichumbi-hotel.jpg","A comfortable Kisoro base near Mgahinga and the Virunga highlands."),l("Arcadia Lodge Lake Bunyonyi","Lake Bunyonyi","1 night","Mid-range","/assets/kisoro-tour/arcadia-lodge.jpg","A peaceful lodge with panoramic views over Lake Bunyonyi and its islands.",["Free WiFi","Restaurant","Lake views","Hot showers"])],
  features: standardFeatures, included: ["Private 4x4 transport","Professional driver-guide","Four nights' accommodation","Gorilla trekking permit (USD 800 value)","Golden monkey tracking","Batwa and coffee experiences","Lake Bunyonyi boat ride","Specified meals and park fees"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Private tour package","Included"],["Gorilla permit","Included (USD 800 value)"],["Golden monkey tracking","Included"],["Cultural and lake activities","Included"]], bookingBenefits: ["Early booking benefits",...standardBenefits], pricingInclusions: ["Four nights' accommodation","All specified meals","Private 4x4 and guide","Gorilla and golden monkey permits","Batwa, coffee and lake experiences","Park fees and transfers"], importantNotes: ["Price based on double occupancy","Single supplement: $350","Luxury upgrade from $500",...standardNotes.slice(1)], permitNote,
};

export const uganda5DayHoliday: ItineraryConfig = {
  title: "5-Day Short Holiday Package", shortTitle: "5-Day Uganda Short Holiday", eyebrow: "Wild beauty in five memorable days", description: "A compact Uganda holiday combining Queen Elizabeth wildlife, the Kazinga Channel, Bwindi gorillas and Lake Bunyonyi.", heroImage: "/assets/5day-holiday/day3.png", duration: "5 days", nights: "4 nights", destination: "Uganda", travelStyle: "Private", price: "$2,910 USD",
  days: [
    d("01","Arrival & Transfer to Queen Elizabeth NP","Entebbe to Queen Elizabeth","/assets/5day-holiday/day3.png",[s("Arrival & journey",["Arrive at Entebbe International Airport","Meet your private WildMed guide","Scenic drive to Queen Elizabeth National Park","Lunch stop en route"],"ri-car-line"),s("Accommodation & evening",["Check into Irungu Forest Safari Lodge","Unwind and settle in","Dinner at the lodge","Briefing about the safari days ahead"],"ri-hotel-line")],"Park insight","Queen Elizabeth is Uganda's most popular safari destination, known for tree-climbing lions, elephants and more than 600 bird species."),
    d("02","Game Drive & Kazinga Channel Cruise","Queen Elizabeth National Park","/assets/5day-holiday/day4.png",[s("Morning game drive",["Game drive in the Ishasha sector","Search for tree-climbing lions","Spot elephants, buffalo and antelopes","Professional guide commentary"],"ri-binoculars-line"),s("Afternoon boat cruise",["Boat cruise on the Kazinga Channel","Hippo and crocodile viewing","Birdwatching across hundreds of species","Wildlife photography opportunities"],"ri-ship-line")],"Wildlife highlight","The tree-climbing lions of Ishasha are a rare phenomenon found in only a few places in Africa."),
    d("03","Gorilla Trekking in Bwindi","Bwindi Impenetrable Forest","/assets/5day-holiday/day5.png",[s("Gorilla trekking experience",["Breakfast and travel to Bwindi","Gorilla trekking briefing","Trek through ancient rainforest","One hour with a mountain gorilla family"],"ri-footprint-line"),s("Evening accommodation",["Check into Ride 4 a Woman Guesthouse","Cozy, budget-friendly accommodation","Rest after the trek","Share stories of the gorilla encounter"],"ri-hotel-line")],"Conservation note","Bwindi is home to almost half of the world's remaining mountain gorillas. Permit fees directly support conservation."),
    d("04","Scenic Tranquility at Lake Bunyonyi","Bwindi to Lake Bunyonyi","/assets/5day-holiday/day7.png",[s("Morning transfer",["Breakfast at the guesthouse","Scenic drive to Lake Bunyonyi","Views across terraced hills","Arrive at Itambira Island Resort"],"ri-car-line"),s("Lake activities",["Explore lake islands by boat","Visit local communities","Relax beside the lake","Sunset photography"],"ri-ship-line")],"Scenic beauty","Lake Bunyonyi means Place of Many Little Birds. Its tranquil waters and 29 islands offer a peaceful close to the safari."),
    d("05","Lake Views & Return to Entebbe","Lake Bunyonyi to Entebbe","/assets/5day-holiday/day8.png",[s("Final morning",["Breakfast overlooking the lake","Last photographs of the views","Optional morning walk","Pack and prepare for departure"],"ri-sun-line"),s("Return journey",["Begin the return to Entebbe","Lunch stop en route","Scenic countryside drive","Airport or hotel drop-off"],"ri-car-line")],"Departure notes","Schedule international flights after 6pm or arrange an overnight in Entebbe for early departures."),
  ],
  highlights: h(["/assets/5day-holiday/day3.png","/assets/5day-holiday/day4.png","/assets/5day-holiday/day5.png","/assets/5day-holiday/day7.png","/assets/5day-holiday/day8.png","/assets/5day-holiday/day6.jpg"],["Queen Elizabeth safari","Kazinga Channel","Bwindi gorillas","Lake Bunyonyi","Uganda countryside","Holiday moments"]),
  lodges: [l("Irungu Forest Safari Lodge","Queen Elizabeth NP","2 nights","Mid-range","/assets/5day-holiday/irungu-lodge.jpg","A relaxed forest-edge safari lodge close to Queen Elizabeth National Park."),l("Ride 4 a Woman Guesthouse","Bwindi","1 night","Community stay","/assets/5day-holiday/ride4woman.jpg","A warm community-run guesthouse supporting local women and families."),l("Itambira Island Resort","Lake Bunyonyi","1 night","Island resort","/assets/5day-holiday/itambira-resort.jpg","A peaceful island stay surrounded by Lake Bunyonyi's calm waters.",["Free WiFi","Restaurant","Lake views","Hot showers"])],
  features: standardFeatures, included: ["Private 4x4 transport","Professional guide","Four nights' accommodation","Gorilla permit (USD 700 value)","Game drive and Kazinga cruise","Lake Bunyonyi activities","Park fees","Specified meals and bottled water"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Private holiday package","Included"],["Gorilla permit","Included (USD 700 value)"],["Game drive and boat cruise","Included"],["Transport and guiding","Included"]], bookingBenefits: ["Value benefits","Flexible start dates",...standardBenefits.slice(1)], pricingInclusions: ["Four nights' accommodation","Private transport and guide","Gorilla trekking permit","Queen Elizabeth safari and boat cruise","Lake Bunyonyi stay","Park fees and transfers"], importantNotes: ["Price based on double occupancy","Single supplement: $300","Luxury upgrade from $500",...standardNotes.slice(1)], permitNote,
};

export const uganda6DayKisoro: ItineraryConfig = {
  title: "6-Day Kisoro Immersive Journey", shortTitle: "6-Day Kisoro Journey", eyebrow: "Untouched Southwestern Uganda", description: "Coffee farms, hill hikes, Lake Mutanda canoeing, Bafumbira and Batwa culture, golden monkeys and Bwindi gorillas in one immersive journey.", heroImage: "/assets/kisoro-6day/day1.png", duration: "6 days", nights: "5 nights", destination: "Kisoro", travelStyle: "Immersive", price: "$2,800 USD",
  days: [
    d("01","Arrival in Kisoro","Entebbe/Kigali to Kisoro","/assets/kisoro-6day/day1.png",[s("Arrival & scenic drive",["Arrive at Entebbe or Kigali Airport","Meet your personal guide","8-9 hour scenic drive to Kisoro","Photo and refreshment stops"],"ri-car-line"),s("Evening in Kisoro",["Check into Mountain Gorilla View Lodge","Dinner with hilltop views","Briefing for the week ahead","Relax overlooking the Virunga Mountains"],"ri-hotel-line")]),
    d("02","Coffee, Hiking & Canoeing","Kisoro adventures","/assets/kisoro-6day/day2.png",[s("Coffee farm experience",["Visit a local Arabica coffee farm","Hands-on harvesting","Learn processing techniques","Freshly brewed coffee tasting"],"ri-cup-line"),s("Outdoor adventures",["Hike Karunga Hill for panoramic views","See Virunga volcanoes and Lake Mutanda","Traditional canoe on Lake Mutanda","Explore hidden islets and birdlife"],"ri-ship-line")]),
    d("03","Culture & Skeleton Island","Cultural immersion day","/assets/kisoro-6day/day3.png",[s("Tailor shop & cultural experience",["Visit a local tailor shop","See traditional Ugandan attire being made","Option for a custom clothing piece","Bafumbira cultural immersion","Traditional dance and storytelling"],"ri-shirt-line"),s("Skeleton Island excursion",["Boat ride to Skeleton Island","See the ancient skeleton-shaped tree","Mountain photography","Peaceful island escape"],"ri-camera-line")]),
    d("04","Golden Monkeys & Batwa Culture","Mgahinga National Park","/assets/kisoro-6day/day4.png",[s("Golden monkey trekking",["Trek in Mgahinga Gorilla National Park","Find rare golden monkey troops","One hour of observation","High-altitude forest experience"],"ri-bear-smile-line"),s("Batwa cultural encounter",["Meet former forest-dwelling Batwa","Guided forest walk with Batwa guides","Learn medicinal plant uses","Traditional singing and dancing"],"ri-community-line")],"Lodge transfer","Stay at Bushara Gate Lodge near Bwindi in preparation for tomorrow's gorilla trek."),
    d("05","Gorilla Trekking in Bwindi","Bwindi Impenetrable Forest","/assets/kisoro-6day/day5.png",[s("Gorilla trekking experience",["Early breakfast and briefing","Enter the UNESCO World Heritage Site","Trek with expert trackers for 1-6 hours","Find a mountain gorilla family","One magical hour with the gorillas"],"ri-footprint-line"),s("Afternoon & celebration",["Return to the lodge for lunch","Rest and process the experience","Review photos and memories","Celebration dinner"],"ri-camera-line")],"Lifetime experience","Seeing mountain gorillas in their natural habitat is a transformative experience that stays with you forever."),
    d("06","Departure","Return to Entebbe/Kigali","/assets/kisoro-6day/day6.png",[s("Morning & final breakfast",["Final breakfast at Bushara Gate Lodge","Pack and prepare for departure","Last moments in the mountains","Farewell to the lodge staff"],"ri-sun-line"),s("Return journey",["Drive to Entebbe or Kigali","Lunch stop en route","Scenic countryside drive","Airport or hotel transfer"],"ri-car-line")]),
  ],
  highlights: h([1,2,3,4,5,6,7,8].map(n=>`/assets/kisoro-6day/day${n}.png`),["Virunga arrival","Coffee country","Lake Mutanda","Bafumbira culture","Golden monkeys","Batwa heritage","Bwindi gorillas","Southwest landscapes"]),
  lodges: [l("Mountain Gorilla View Lodge","Kisoro","3 nights","Mid-range","/assets/kisoro-6day/mountain-gorilla-lodge.png","A hilltop stay with sweeping views toward the Virunga Mountains."),l("Bushara Gate Lodge","Bwindi","2 nights","Mid-range","/assets/kisoro-6day/bushara-lodge.jpg","A comfortable forest gateway lodge positioned for gorilla trekking.")],
  features: standardFeatures, included: ["Private transport and guide","Five nights' accommodation","Coffee farm and cultural experiences","Karunga Hill hike","Lake Mutanda canoeing","Golden monkey tracking","Batwa experience","Gorilla permit and park fees"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Six-day tour package","Included"],["Gorilla permit","Included"],["Golden monkey tracking","Included"],["Cultural and lake activities","Included"]], bookingBenefits: standardBenefits, pricingInclusions: ["Five nights' accommodation","Private transport and guide","All listed cultural and outdoor activities","Gorilla and golden monkey permits","Specified meals and park fees"], importantNotes: ["Price based on double occupancy","Single supplement: $450","Upgrade options from $500",...standardNotes.slice(1)], permitNote,
};

export const rwanda7Day: ItineraryConfig = {
  title: "7-Day Rwanda-Uganda Expedition", shortTitle: "7-Day Rwanda-Uganda Expedition", eyebrow: "Grand tour · Two countries", description: "Golden monkeys, Bwindi gorillas, Queen Elizabeth wildlife, Kyambura chimpanzees and Lake Mburo on a custom cross-border safari.", heroImage: "/assets/8day trip/8day1.jpg", duration: "7 days", nights: "6 nights", destination: "Rwanda + Uganda", travelStyle: "Custom", price: "$3,800 USD",
  days: [
    d("01","Arrival & Transfer","Kigali to Volcanoes NP","/assets/8day trip/8day1.jpg",[s("Journey highlights",["Arrival at Kigali International Airport","Scenic drive to Volcanoes National Park","Golden monkey tracking briefing","Dinner with mountain views"],"ri-car-line"),s("Important notes",["Altitude: 2,500-4,500 metres","Pack warm evening clothing","Charge camera batteries","Keep passport and permits ready"],"ri-information-line")]),
    d("02","Golden Monkeys & Border Crossing","Rwanda to Uganda","/assets/8day trip/8day2.jpg",[s("Morning activities",["Early breakfast","Golden monkey tracking","Photography of endangered primates","Bamboo forest exploration"],"ri-bear-smile-line"),s("Afternoon journey",["Cross into Uganda","Scenic drive to Bwindi","Lodge check-in and orientation","Gorilla trekking briefing"],"ri-road-map-line")],"Wildlife insight","Golden monkeys are endangered and found only in the Virunga massif. Their acrobatics in bamboo forests are spectacular."),
    d("03","Gorilla Trekking Experience","Bwindi Impenetrable NP","/assets/8day trip/8day3.jpg",[s("Gorilla trekking",["Early briefing with rangers","2-6 hour forest trek","One hour with a gorilla family","Professional photography guidance"],"ri-footprint-line"),s("Afternoon options",["Batwa cultural experience","Community walk and crafts","Transfer to Queen Elizabeth NP","Optional lodge relaxation"],"ri-community-line")],"Trekking essentials","Bring sturdy boots, a rain jacket and gloves. Walking sticks are provided and several trek difficulty levels are available."),
    d("04","Queen Elizabeth Safari","Queen Elizabeth NP","/assets/8day trip/8day4.jpg",[s("Morning game drive",["Dawn safari in Kasenyi plains","Search for tree-climbing lions","See elephant and buffalo herds","Professional guide commentary"],"ri-binoculars-line"),s("Afternoon boat cruise",["Kazinga Channel wildlife cruise","Hippo and crocodile viewing","Birdwatching across 300+ species","Sunset photography"],"ri-ship-line")]),
    d("05","Chimps & Community","Kyambura Gorge","/assets/8day trip/8day5.jpg",[s("Chimpanzee tracking",["Descend into Kyambura Gorge","2-3 hour chimp tracking","Observe feeding behaviours","Forest ecosystem education"],"ri-bear-smile-line"),s("Community experience",["Local village visit","Traditional craft demonstrations","Twin Lakes sunset viewing","Cultural exchange activities"],"ri-community-line")]),
    d("06","Lake Mburo Safari","Lake Mburo NP","/assets/8day trip/8day6.jpg",[s("Wildlife viewing",["Morning game drive for zebras","Boat cruise for hippos and birds","Ankole cattle ranch visit","Guided nature walk"],"ri-binoculars-line"),s("Photography highlights",["Zebra herds on open plains","Impala and topi antelopes","Water birds at the lake shore","Traditional long-horned cattle"],"ri-camera-line")]),
    d("07","Return & Crocodile Farm","Lake Mburo to Entebbe","/assets/8day trip/8day7.jpg",[s("Return journey",["Scenic drive to Kampala","Uganda Equator crossing","Local craft market stops","Lunch en route"],"ri-car-line"),s("Final experience",["Uganda Crocs LTD visit","Crocodile farming education","Optional crocodile meat tasting","Transfer to Entebbe Airport"],"ri-community-line")],"Departure notes","Schedule flights after 6pm to allow time for the final activities and ensure souvenirs are packed."),
  ],
  highlights: h([1,2,3,4,5,6,7,8].map(n=>`/assets/8day trip/8day${n}.jpg`),["Volcanoes National Park","Golden monkeys","Bwindi gorillas","Queen Elizabeth safari","Kyambura chimpanzees","Lake Mburo","Ankole culture","Cross-border journey"]),
  lodges: [l("Volcanoes Lodge Stay","Volcanoes National Park","1 night","Comfort","/assets/8day trip/8day1.jpg","A mountain base for the golden monkey experience."),l("Bwindi Forest Lodge","Bwindi","2 nights","Comfort","/assets/8day trip/8day3.jpg","A forest lodge positioned for the gorilla trek."),l("Queen Elizabeth Safari Lodge","Queen Elizabeth NP","2 nights","Safari lodge","/assets/8day trip/8day4.jpg","A wildlife-focused stay near game-drive and boat-cruise routes."),l("Lake Mburo Lodge","Lake Mburo NP","1 night","Safari lodge","/assets/8day trip/8day6.jpg","A peaceful savanna stay among zebra and acacia woodland.")],
  features: standardFeatures, included: ["Cross-border private transport","Professional guide","Six nights' accommodation","Golden monkey and gorilla permits","Queen Elizabeth game drive and cruise","Chimpanzee tracking","Lake Mburo activities","Park fees and transfers"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Seven-day custom safari","Included"],["Primate permits","Included"],["Game drives and boat cruises","Included"],["Cross-border transport","Included"]], bookingBenefits: ["Early booking benefits",...standardBenefits], pricingInclusions: ["Six nights' accommodation","All listed primate and wildlife activities","Professional guide and private transport","Park fees and boat cruises","Airport transfers and specified meals"], importantNotes: ["Cross-border documents are required","Price based on double occupancy",...standardNotes.slice(1)], permitNote,
};

export const uganda8DayLuxury: ItineraryConfig = {
  title: "8-Day Luxury Uganda Safari", shortTitle: "8-Day Luxury Uganda Safari", eyebrow: "Uganda in style · Chimps to gorillas", description: "A refined primate and wildlife circuit through Kibale, Queen Elizabeth and Bwindi, paired with Uganda's iconic luxury lodges.", heroImage: "/assets/8day-luxury/luxury1.png", duration: "8 days", nights: "7 nights", destination: "Uganda", travelStyle: "Luxury", price: "$9,400 USD",
  days: [
    d("01","Arrival in Entebbe","Luxury arrival","/assets/8day-luxury/luxury1.png",[s("Arrival & welcome",["Arrive at Entebbe International Airport","Private meet and greet","Luxury transfer to Hotel No.5","Welcome dinner and safari briefing"],"ri-plane-line"),s("Luxury accommodation",["Stay at Hotel No.5 Entebbe","Premier luxury hotel experience","Unwind after your international flight","Personalized service from arrival"],"ri-hotel-line")],"Luxury touch","Hotel No.5 is Entebbe's premier luxury hotel, with exquisite service, gourmet dining and a restful start to the safari."),
    d("02–03","Chimpanzee Trekking in Kibale","Kibale Forest National Park","/assets/8day-luxury/luxury2.png",[s("Primate experience",["Travel to Kibale Forest","Guided chimpanzee trekking","See 13 primate species","Tropical forest nature walks","Cultural village visits"],"ri-bear-smile-line"),s("Luxury forest lodge",["Stay at Primate Lodge Kibale","Forest canopy views","Gourmet local meals","Evening wildlife sounds","Lodge inside the park"],"ri-hotel-line")],"Primate capital","Kibale has Africa's highest concentration of primates. Primate Lodge provides privileged access from the heart of the forest."),
    d("04–05","Wildlife in Queen Elizabeth NP","Queen Elizabeth National Park","/assets/8day-luxury/luxury4.png",[s("Wildlife adventures",["Morning and afternoon game drives","Search for tree-climbing lions","Elephants in Kasenyi plains","Kazinga Channel boat cruise","Hippo and crocodile viewing"],"ri-binoculars-line"),s("Iconic safari lodge",["Stay at Mweya Safari Lodge","Panoramic Kazinga Channel views","Infinity pool overlooking wildlife","Fine dining","Iconic park location"],"ri-hotel-line")],"Wildlife diversity","Queen Elizabeth has 95 mammal species and more than 600 bird species, with excellent viewing from Mweya Lodge."),
    d("06–07","Gorilla Trekking in Bwindi","Bwindi Impenetrable National Park","/assets/8day-luxury/luxury6.png",[s("Gorilla encounter",["Travel to Bwindi","Ranger briefing","Trek through ancient forest","One hour with a gorilla family","A life-changing encounter"],"ri-footprint-line"),s("Serene forest lodge",["Stay at Buhoma Lodge","Forest canopy and mountain vistas","Luxury cottages with fireplaces","Spa treatments available","Upscale lodge service"],"ri-hotel-line")],"Conservation success","Bwindi protects nearly half of the world's mountain gorillas. Your visit supports critical conservation efforts."),
    d("08","Return to Entebbe","Journey home","/assets/8day-luxury/luxury8.png",[s("Final morning",["Breakfast overlooking the forest","Last moments at the lodge","Souvenir shopping","Farewell from the lodge team"],"ri-sun-line"),s("Return journey",["Scenic drive to Entebbe","Premium lunch stop","Airport drop-off","Optional Entebbe or Kampala hotel transfer"],"ri-car-line")],"Departure notes","Schedule international flights after 7pm. An additional night at Hotel No.5 can be arranged."),
  ],
  highlights: h([1,2,3,4,5,6,7,8].map(n=>`/assets/8day-luxury/luxury${n}.png`),["Luxury arrival","Kibale forest","Chimpanzee encounter","Queen Elizabeth","Kazinga Channel","Bwindi forest","Mountain gorillas","Uganda farewell"]),
  lodges: [l("Hotel No.5","Entebbe","1 night","Luxury","/assets/8day-luxury/hotel-no5.jpg","An intimate boutique hotel offering a polished arrival in Uganda.",["Free WiFi","Restaurant","Pool","Spa"]),l("Primate Lodge Kibale","Kibale","2 nights","Luxury","/assets/8day-luxury/primate-lodge.jpg","A forest lodge within Kibale National Park, close to chimpanzee trails.",["Free WiFi","Restaurant","Forest views","Hot showers"]),l("Mweya Safari Lodge","Queen Elizabeth NP","2 nights","Luxury","/assets/8day-luxury/mweya-lodge.jpg","An iconic safari lodge overlooking the Kazinga Channel.",["Free WiFi","Restaurant","Pool","Scenic views"]),l("Buhoma Lodge","Bwindi","2 nights","Luxury","/assets/8day-luxury/buhoma-lodge.jpg","A serene upscale lodge with forest vistas and warm fireside comfort.",["Free WiFi","Restaurant","Forest views","Spa"])],
  features: [{icon:"ri-vip-crown-line",title:"Luxury tour",text:"Premium lodges and personalized service"},{icon:"ri-calendar-event-line",title:"Flexible dates",text:"Start on dates suited to your party"},{icon:"ri-settings-3-line",title:"Fully customizable",text:"Tailor pacing, rooms and experiences"},{icon:"ri-group-line",title:"Group focused",text:"Private arrangements for your party"}], included: ["Luxury accommodation","Private transport and guide","Chimpanzee and gorilla permits","Game drives and Kazinga cruise","All specified meals","Park entrance fees","Airport transfers","Bottled water"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Luxury safari package","Included"],["Premium lodges","Included"],["Primate permits","Included (gorilla permit USD 700 value)"],["Private transport and activities","Included"]], bookingBenefits: ["Premium booking benefits","Priority room selection","Dedicated trip planner","Flexible payment options"], pricingInclusions: ["Seven nights' luxury accommodation","All meals specified","Private 4x4 and guide","Chimpanzee and gorilla permits","Game drives and boat cruise","Park fees and transfers"], importantNotes: ["Price based on double occupancy","Single supplement: $1,000","Luxury upgrades from $1,800",...standardNotes.slice(1)], permitNote,
};

export const uganda8DayCrossBorder: ItineraryConfig = {
  title: "8-Day Gorilla Safari: Uganda & Rwanda", shortTitle: "8-Day Uganda & Rwanda Safari", eyebrow: "Two countries · One life-changing journey", description: "Rhinos, Murchison Falls, Kibale chimpanzees, Queen Elizabeth wildlife, Bwindi gorillas, Lake Bunyonyi and Kigali in one cross-border expedition.", heroImage: "/assets/8day-safari/day1.png", duration: "8 days", nights: "7 nights", destination: "Uganda + Rwanda", travelStyle: "Private", price: "$3,780 USD",
  days: [
    d("01","Arrival in Entebbe → Kampala","Entebbe to Kampala","/assets/8day-safari/day1.png",[s("Arrival & transfer",["Arrive at Entebbe International Airport","Warm welcome by your private guide","Transfer to Kampala","Settle into your accommodation"],"ri-plane-line"),s("Evening & accommodation",["Check into Marie's Royale Hotel","Safari briefing","Dinner at the hotel","Rest after the journey"],"ri-hotel-line")],"First night insight","Kampala blends modern development with rich cultural heritage and offers a gentle introduction to East Africa."),
    d("02","Ziwa Rhino Sanctuary → Murchison Falls","Kampala to Murchison Falls NP","/assets/8day-safari/day2.png",[s("Rhino encounter",["Visit Ziwa Rhino Sanctuary","See Uganda's only wild rhinos","Guided ranger walk","Photography opportunities"],"ri-binoculars-line"),s("Murchison Falls journey",["Continue to Murchison Falls NP","Check into Nkundwa Nile View Lodge","Evening Nile views","Sunset dinner"],"ri-road-map-line")],"Conservation insight","Ziwa is a successful project working to reintroduce rhinos to Uganda's national parks after their extinction in the 1980s."),
    d("03","Game Drive & Murchison Falls Cruise","Murchison Falls NP","/assets/8day-safari/day3.png",[s("Morning game drive",["Early game drive","Search for elephants and giraffes","Antelope and buffalo viewing","Birdwatching"],"ri-binoculars-line"),s("Afternoon boat cruise",["Boat cruise on the Nile","Cruise to the base of Murchison Falls","Spot hippos and crocodiles","Waterfall photography"],"ri-ship-line")],"Natural wonder","The Nile forces through a seven-metre gap and plunges 43 metres at Murchison Falls."),
    d("04","Chimpanzee Tracking in Kibale","Murchison Falls to Kibale","/assets/8day-safari/day4.png",[s("Journey to Kibale",["Scenic drive to Kibale","Arrive at Kibale Forest Lodge","Lunch and briefing","Afternoon chimpanzee tracking"],"ri-car-line"),s("Primate experience",["Track chimpanzees","One hour with a chimp family","See other primate species","Evening lodge relaxation"],"ri-bear-smile-line")],"Primate capital","Kibale holds 13 primate species and 375 bird species, with one of the world's highest primate densities."),
    d("05","Queen Elizabeth National Park","Kibale to Queen Elizabeth NP","/assets/8day-safari/day5.png",[s("Transfer & arrival",["Morning drive to Queen Elizabeth NP","Check into Pumba Safari Cottages","Lunch with park views","Afternoon relaxation"],"ri-car-line"),s("Evening game drive",["Late afternoon safari","Explore savanna plains","Look for tree-climbing lions","See buffalo and warthogs"],"ri-binoculars-line")],"Unique wildlife","Queen Elizabeth is famous for the tree-climbing lions of Ishasha, which rest in fig trees during the day."),
    d("06","Ishasha & Scenic Drive to Bwindi","Queen Elizabeth to Bwindi","/assets/8day-safari/day6.png",[s("Ishasha exploration",["Morning game drive","Search for tree-climbing lions","Photograph unique behaviour","Other wildlife sightings"],"ri-binoculars-line"),s("Scenic highlands drive",["Journey to Bwindi","Drive through the highlands","Check into Rushaga Gorilla Lodge","Gorilla trekking briefing"],"ri-road-map-line")],"Gorilla preparation","The evening briefing covers gorilla behaviour, trekking rules and what to expect in Bwindi's misty forest."),
    d("07","Gorilla Trekking → Lake Bunyonyi","Bwindi to Lake Bunyonyi","/assets/8day-safari/day7.png",[s("Gorilla trekking",["Morning trek in Bwindi","Find a mountain gorilla family","One hour with the gentle giants","Return for lunch"],"ri-footprint-line"),s("Lake Bunyonyi transfer",["Travel to Lake Bunyonyi","Check into Itambira Island Resort","Relax by the lake","Reflect on the gorilla experience"],"ri-ship-line")],"Life-changing experience","Meeting endangered mountain gorillas in their natural habitat is an unforgettable connection."),
    d("08","Cross to Rwanda → Kigali Memorial","Uganda to Rwanda","/assets/8day-safari/day8.png",[s("Border crossing",["Breakfast with lake views","Cross into Rwanda","Scenic drive to Kigali","Experience Rwanda's capital"],"ri-road-map-line"),s("Kigali & memorial",["Visit Kigali Genocide Memorial","Learn about Rwanda's history","Lunch in Kigali","Airport or hotel drop-off"],"ri-community-line")],"Journey conclusion","The Kigali memorial provides historical context to Rwanda's recovery. Schedule flights for the evening."),
  ],
  highlights: h([1,2,3,4,5,6,7,8].map(n=>`/assets/8day-safari/day${n}.png`),["Kampala arrival","Ziwa rhinos","Murchison Falls","Kibale chimpanzees","Queen Elizabeth","Ishasha lions","Bwindi gorillas","Kigali memorial"]),
  lodges: [l("Marie's Royale Hotel","Kampala","1 night","Comfort","/assets/8day-safari/maries-royale.jpg","A comfortable Kampala introduction."),l("Nkundwa Nile View Lodge","Murchison Falls","2 nights","Safari lodge","/assets/8day-safari/nkundwa-lodge.jpg","A Nile-facing base for game drives and the falls."),l("Kibale Forest Lodge","Kibale","1 night","Forest lodge","/assets/8day-safari/kibale-lodge.jpg","A forest base close to chimpanzee tracking."),l("Pumba Safari Cottages","Queen Elizabeth NP","1 night","Safari cottages","/assets/8day-safari/pumba-cottages.jpg","Relaxed cottages near the park."),l("Rushaga Gorilla Lodge","Bwindi","1 night","Mid-range","/assets/8day-safari/rushaga-lodge.png","A trekking base near park headquarters."),l("Itambira Island Resort","Lake Bunyonyi","1 night","Island resort","/assets/8day-safari/itambira-resort.jpg","A tranquil island retreat on Lake Bunyonyi.",["Free WiFi","Restaurant","Lake views","Hot showers"])],
  features: [{icon:"ri-earth-line",title:"Two countries",text:"Travel across Uganda and Rwanda"},{icon:"ri-bear-smile-line",title:"Primate encounters",text:"Chimpanzees and mountain gorillas"},{icon:"ri-car-line",title:"Private transport",text:"Dedicated safari vehicle and guide"},{icon:"ri-check-double-line",title:"All-inclusive",text:"Core activities, stays and permits arranged"}], included: ["Private cross-border transport","Seven nights' accommodation","Professional guide","Rhino walk","Game drives and Nile cruise","Chimpanzee and gorilla permits","Park fees","Specified meals and water"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Cross-border safari package","Included"],["Primate and rhino permits","Included"],["Game drives and cruises","Included"],["Accommodation and transport","Included"]], bookingBenefits: ["Early booking benefits",...standardBenefits], pricingInclusions: ["Seven nights' accommodation","Private 4x4 and guide","Rhino, chimpanzee and gorilla experiences","Game drives and boat cruise","Border transfers and park fees"], importantNotes: ["Price based on double occupancy","Single supplement: $420","Optional upgrades from $1,000","Cross-border documents required",...standardNotes.slice(1)], permitNote,
};

export const uganda8DayGrandLuxury: ItineraryConfig = {
  title: "8-Day Luxury Uganda Safari", shortTitle: "8-Day Uganda Luxury Safari", eyebrow: "Uganda's wild majesty in style", description: "Premium hotels and forest lodges frame chimpanzees, Queen Elizabeth wildlife, the Kazinga Channel and a mountain gorilla encounter.", heroImage: "/assets/luxury-uganda/lux1.png", duration: "8 days", nights: "7 nights", destination: "Uganda", travelStyle: "Private luxury", price: "$6,240 USD",
  days: [
    d("01","Arrival in Entebbe – Transfer to Kampala","Entebbe to Kampala","/assets/luxury-uganda/lux1.png",[s("Arrival & transfer",["Arrive at Entebbe Airport","Personal guide welcome","Transfer to Sheraton Kampala","Luxury hotel check-in"],"ri-plane-line"),s("Optional activities",["Bahá'í Temple and Uganda Martyrs' Shrine","Local market exploration","Indian cuisine experience","Evening hotel relaxation"],"ri-building-line")],"Luxury accommodation","Sheraton Kampala provides premium comfort, fine dining and city views."),
    d("02","Journey to Kibale National Park","Kampala to Kibale NP","/assets/luxury-uganda/lux2.png",[s("Scenic journey",["Breakfast at Sheraton Kampala","Drive to Kibale","Cross Uganda's countryside","Arrive at Chimpundu Lodge"],"ri-car-line"),s("Afternoon activities",["Settle into the forest lodge","Nature walk","Cultural village visit","Evening at leisure"],"ri-walk-line")],"Primate paradise","Kibale has one of the world's highest primate densities, with 13 species."),
    d("03","Chimpanzee Trekking in Kibale","Kibale National Park","/assets/luxury-uganda/lux3.png",[s("Chimpanzee encounter",["Morning chimpanzee trek","Guided forest walk","Observe chimpanzees in habitat","Photography opportunities","Primate education"],"ri-bear-smile-line"),s("Leisure time",["Return for lunch","Afternoon lodge relaxation","Forest viewing from your balcony","Evening under the canopy"],"ri-hotel-line")],"Conservation insight","Your visit supports chimpanzee conservation and local communities through sustainable tourism."),
    d("04","Queen Elizabeth National Park","Kibale to Queen Elizabeth NP","/assets/luxury-uganda/lux4.png",[s("Transfer & arrival",["Breakfast at Chimpundu Lodge","Drive to Queen Elizabeth NP","Picturesque countryside","Arrive at Mweya Safari Lodge"],"ri-car-line"),s("Afternoon safari",["Panoramic lodge check-in","Afternoon game drive","Search for iconic wildlife","Sunset over Kazinga Channel"],"ri-binoculars-line")],"Spectacular location","Mweya Safari Lodge overlooks the Kazinga Channel and Rwenzori Mountains."),
    d("05","Kazinga Channel & Tree-Climbing Lions","Queen Elizabeth NP","/assets/luxury-uganda/lux5.png",[s("Morning activities",["Kazinga Channel boat cruise","Hippo and crocodile viewing","Birdwatching across 300+ species","Aquatic wildlife photography"],"ri-ship-line"),s("Afternoon safari",["Ishasha sector game drive","Search for tree-climbing lions","Elephant and buffalo sightings","Professional commentary"],"ri-binoculars-line")],"Photography highlight","Queen Elizabeth's tree-climbing lions are found in only a few places in Africa."),
    d("06","Journey to Bwindi","Queen Elizabeth to Bwindi","/assets/luxury-uganda/lux6.png",[s("Scenic transfer",["Breakfast with panoramic views","Drive to Bwindi","Enter the UNESCO World Heritage Site","Check into Mahogany Springs"],"ri-road-map-line"),s("Preparation & relaxation",["Settle at the forest edge","Gorilla trekking briefing","Prepare equipment","Relax in tranquillity"],"ri-hotel-line")],"Gorilla sanctuary","Bwindi protects nearly half the world's remaining mountain gorillas."),
    d("07","Mountain Gorilla Trekking","Bwindi Impenetrable NP","/assets/luxury-uganda/lux7.png",[s("Gorilla experience",["Early breakfast","Transfer to headquarters","Ranger briefing","Trek to a gorilla family","One magical hour"],"ri-footprint-line"),s("Celebration & relaxation",["Return for lunch","Afternoon at leisure","Review photographs","Celebratory dinner"],"ri-camera-line")],"Lifetime achievement","Gorilla trekking is one of the world's most profound wildlife experiences."),
    d("08","Return to Entebbe","Bwindi to Entebbe","/assets/luxury-uganda/lux8.png",[s("Morning departure",["Final breakfast","Scenic drive to Entebbe","Last countryside views","Lunch stop"],"ri-sun-line"),s("Journey conclusion",["Late-afternoon arrival","Airport or hotel drop-off","Farewell from your guide","End of safari"],"ri-plane-line")],"Travel planning","Schedule flights after 6pm or stay overnight in Entebbe."),
  ],
  highlights: h([1,2,3,4,5,6,7,8].map(n=>`/assets/luxury-uganda/lux${n}.png`),["Kampala welcome","Kibale forest","Chimpanzee trek","Queen Elizabeth","Kazinga Channel","Bwindi arrival","Gorilla trekking","Uganda farewell"]),
  lodges: [l("Sheraton Kampala Hotel","Kampala","1 night","Luxury","/assets/luxury-uganda/sheraton-kampala.jpg","A five-star city stay for a comfortable arrival.",["Free WiFi","Restaurant","Pool","Spa"]),l("Chimpundu Lodge","Kibale","2 nights","Luxury","/assets/luxury-uganda/chimpundu-lodge.jpg","A serene forest lodge close to chimpanzee trekking.",["Free WiFi","Restaurant","Forest views","Hot showers"]),l("Mweya Safari Lodge","Queen Elizabeth NP","2 nights","Luxury","/assets/luxury-uganda/mweya-lodge.jpg","Panoramic views across the Kazinga Channel.",["Free WiFi","Restaurant","Pool","Scenic views"]),l("Mahogany Springs Lodge","Bwindi","2 nights","Luxury","/assets/luxury-uganda/mahogany-springs.jpg","A refined lodge on the edge of Bwindi forest.",["Free WiFi","Restaurant","Forest views","Spa"])],
  features: [{icon:"ri-vip-crown-line",title:"Private luxury tour",text:"Exclusive transport and premium stays"},{icon:"ri-calendar-event-line",title:"Flexible start dates",text:"Travel when it suits you"},{icon:"ri-settings-3-line",title:"Fully customizable",text:"Shape pacing and experiences"},{icon:"ri-user-heart-line",title:"Solo traveller friendly",text:"Personal service throughout"}], included: ["Private luxury 4x4","Seven nights' premium accommodation","Professional driver-guide","Chimpanzee and gorilla permits","Game drives and Kazinga cruise","All specified meals","Park fees","Airport transfers"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Private luxury safari","Included"],["Premium accommodation","Included"],["Primate permits","Included (gorilla permit USD 700 value)"],["Private activities and guiding","Included"]], bookingBenefits: ["Early-booking premium benefits","Priority lodge selection","Dedicated trip planning","Flexible payment schedule"], pricingInclusions: ["Seven nights' luxury accommodation","Private 4x4 and guide","Chimpanzee and gorilla trekking","Game drives and Kazinga cruise","Park fees, meals and transfers"], importantNotes: ["Price based on double occupancy","Single supplement: $850","Premium upgrades from $1,000",...standardNotes.slice(1)], permitNote,
};

export const uganda11DayCrossBorder: ItineraryConfig = {
  title: "11-Day Uganda & Rwanda Safari", shortTitle: "11-Day Uganda & Rwanda Safari", eyebrow: "Gorillas · Chimps · Volcanoes", description: "An immersive cross-border safari through Rwanda and Uganda, combining savanna wildlife, primate encounters, volcanic landscapes and meaningful cultural experiences.", heroImage: "/assets/uganda-rwanda-11day/day6-bwindi-gorillas.png", duration: "11 days", nights: "10 nights", destination: "Uganda + Rwanda", travelStyle: "Private", price: "$4,800 USD",
  days: [
    d("01","Arrival in Kigali, Rwanda","Kigali International Airport","/assets/uganda-rwanda-11day/day1-kigali.png",[s("Arrival & welcome",["Arrive at Kigali International Airport","Meet your private WildMed guide","Transfer to Five to Five Hotel","Relax after your journey"],"ri-plane-line"),s("Evening city tour",["Explore Kigali's clean, safe streets","Visit local markets","Learn about Rwanda's transformation","Dinner at the hotel"],"ri-building-line")],"Rwanda insight","Kigali is one of Africa's cleanest and safest capitals, blending modernity with tradition."),
    d("02","Lake Mburo National Park, Uganda","Cross border to Uganda","/assets/uganda-rwanda-11day/day2-lake-mburo.png",[s("Border crossing & transfer",["Cross into Uganda","Drive to Lake Mburo National Park","Check into Hyena Hill Lodge","Lunch and relaxation"],"ri-road-map-line"),s("Afternoon game drive",["Late-afternoon game drive","See zebra, impala and buffalo","Photograph acacia landscapes","Enjoy the sunset"],"ri-binoculars-line")],"Wildlife note","Lake Mburo is Uganda's smallest savanna park, with a high wildlife density and the country's only national-park zebra population."),
    d("03–04","Queen Elizabeth National Park","Two full safari days","/assets/uganda-rwanda-11day/day3-4-queen-elizabeth.png",[s("Game drives & wildlife",["Morning and evening game drives","Search for Ishasha's tree-climbing lions","See elephants on the Kasenyi plains","Look for more than 600 bird species"],"ri-binoculars-line"),s("Kazinga Channel cruise",["Cruise the Kazinga Channel","See hippos and crocodiles","Exceptional shoreline birding","Stay at Enshama Game Lodge"],"ri-ship-line")],"Park diversity","This 1,978-square-kilometre park combines savanna, wetlands, forest and lakes, supporting 95 mammal and over 600 bird species."),
    d("05","Chimpanzee Tracking & Bwindi Transfer","Kalinzu Forest to Bwindi","/assets/uganda-rwanda-11day/day5-chimpanzees.png",[s("Chimpanzee tracking",["Track chimpanzees in Kalinzu Forest","Spend two to four hours in the forest","Observe a chimpanzee community for one hour","See other primate species"],"ri-bear-smile-line"),s("Transfer to Bwindi",["Drive to Bwindi Impenetrable Forest","Check into Rushaga Gorilla Lodge","Attend the gorilla briefing","Rest for tomorrow's trek"],"ri-car-line")],"Forest insight","Kalinzu protects about 320 chimpanzees in six communities and offers an intimate, less-crowded tracking experience."),
    d("06","Gorilla Trekking in Bwindi","Bwindi Impenetrable Forest","/assets/uganda-rwanda-11day/day6-bwindi-gorillas.png",[s("Gorilla trekking",["Early ranger briefing","Trek through the ancient forest","Find a habituated gorilla family","Spend one unforgettable hour with them"],"ri-footprint-line"),s("Afternoon transfer",["Return to the lodge for lunch","Transfer to Itambira Island Resort","Relax beside Lake Bunyonyi","Dinner at the resort"],"ri-hotel-line")],"Conservation insight","Bwindi protects about 459 mountain gorillas—nearly half the global population—and permit fees directly support their conservation."),
    d("07","Lake Bunyonyi Relaxation","Cultural & relaxation day","/assets/uganda-rwanda-11day/day7-lake-bunyonyi.png",[s("Lake exploration",["Traditional canoe excursion","Visit island villages","Explore the lake's 29 islands","Birdwatch and photograph the landscapes"],"ri-ship-line"),s("Leisure & culture",["Guided nature walks","Relax at the resort","Meet local communities","Evening bonfire"],"ri-community-line")],"Lake insight","Lake Bunyonyi sits around 900 metres above sea level, is considered Africa's second-deepest lake and is free from bilharzia."),
    d("08–09","Mount Bisoke Hike, Rwanda","Volcano adventure","/assets/uganda-rwanda-11day/day8-9-mt-bisoke.png",[s("Volcano hike",["Cross back into Rwanda","Climb Mount Bisoke to 3,711 metres","See the summit crater lake","Take in Virunga views"],"ri-walk-line"),s("Ruhengeri stay",["Stay at Isange Paradise Resort","Recover after the hike","Enjoy the mountain setting","Prepare for golden monkey tracking"],"ri-hotel-line")],"Hiking note","The Mount Bisoke round trip normally takes six to seven hours and requires good fitness."),
    d("10","Golden Monkey Trekking","Volcanoes National Park","/assets/uganda-rwanda-11day/day10-golden-monkeys.png",[s("Morning trek",["Enter Volcanoes National Park","Track golden monkeys through bamboo forest","Photograph their acrobatic behaviour","Learn about primate conservation"],"ri-bear-smile-line"),s("Afternoon at leisure",["Optional cultural visit","Rest at the resort","Shop for local souvenirs","Farewell dinner"],"ri-shopping-bag-line")],"Rare primates","Endangered golden monkeys survive only in the Virunga massif, making this a uniquely regional wildlife encounter."),
    d("11","Kigali Memorial & Departure","Return to Kigali","/assets/uganda-rwanda-11day/day1-kigali.png",[s("Kigali Genocide Memorial",["Visit the memorial","Learn Rwanda's history","Understand its reconciliation journey","Take time for reflection"],"ri-heart-line"),s("City & departure",["Final Kigali city tour","Souvenir shopping","Lunch in the city","Transfer to the airport"],"ri-plane-line")],"Memorial significance","The Kigali Genocide Memorial honours victims while documenting Rwanda's history and extraordinary path toward reconciliation."),
  ],
  highlights: h(["/assets/uganda-rwanda-11day/day6-bwindi-gorillas.png","/assets/uganda-rwanda-11day/day3-4-queen-elizabeth.png","/assets/uganda-rwanda-11day/day5-chimpanzees.png","/assets/uganda-rwanda-11day/day8-9-mt-bisoke.png","/assets/uganda-rwanda-11day/day10-golden-monkeys.png","/assets/uganda-rwanda-11day/day7-lake-bunyonyi.png"],["Bwindi gorillas","Queen Elizabeth wildlife","Kalinzu chimpanzees","Mount Bisoke","Golden monkeys","Lake Bunyonyi"]),
  lodges: [l("Five to Five Hotel","Kigali","1 night","Comfort","/assets/uganda-rwanda-11day/accommodation-kigali.jpg","A welcoming Kigali base close to the airport."),l("Hyena Hill Lodge","Lake Mburo","1 night","Safari lodge","/assets/uganda-rwanda-11day/accommodation-lake-mburo.jpg","A peaceful lodge overlooking Lake Mburo's rolling savanna."),l("Enshama Game Lodge","Queen Elizabeth NP","2 nights","Safari lodge","/assets/uganda-rwanda-11day/accommodation-queen-elizabeth.jpeg","A comfortable base for game drives and the Kazinga Channel."),l("Rushaga Gorilla Lodge","Bwindi","1 night","Mid-range","/assets/uganda-rwanda-11day/accommodation-bwindi.jpg","A forest-side lodge positioned for gorilla trekking."),l("Itambira Island Resort","Lake Bunyonyi","2 nights","Island resort","/assets/uganda-rwanda-11day/accommodation-lake-bunyonyi.jpg","A tranquil island retreat for canoeing and cultural visits."),l("Isange Paradise Resort","Ruhengeri","3 nights","Mountain resort","/assets/uganda-rwanda-11day/accommodation-ruhengeri.jpg","A relaxed base for Mount Bisoke and golden monkey adventures.")],
  features: standardFeatures, included: ["Private cross-border transport","Professional driver-guide","Ten nights' accommodation","Lake Mburo and Queen Elizabeth safaris","Kazinga Channel cruise","Chimpanzee, gorilla and golden monkey permits","Mount Bisoke hike","Lake Bunyonyi activities","Park and border support"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Eleven-day tour package","USD 4,800 per person"],["Gorilla permit","Included"],["Primate permits and Mount Bisoke hike","Included"],["Accommodation and specified meals","Included"],["Private cross-border transport","Included"]], bookingBenefits: standardBenefits, pricingInclusions: ["Ten nights' accommodation","Private transport and guide","All listed wildlife, primate and cultural activities","Park fees and permits","Specified meals and airport transfers"], importantNotes: ["Price based on double occupancy","Single supplement: $500","Premium upgrades from $750","Deposit: $2,200 per person","Balance due 60 days before arrival","Rwanda/Uganda visa: USD $50 where applicable","Optional activities from $100",...standardNotes.slice(1)], permitNote,
};

export const uganda11DayLuxury: ItineraryConfig = {
  title: "11-Day Luxury Primate Safari", shortTitle: "11-Day Luxury Primate Safari", eyebrow: "Immerse yourself in the wild heart of Africa", description: "A premium primate journey through Kibale, Queen Elizabeth and Mgahinga, with extended chimpanzee and gorilla experiences and carefully selected lodges.", heroImage: "/assets/15 day trip/15day1.jpg", duration: "11 days", nights: "10 nights", destination: "Uganda", travelStyle: "Luxury", price: "$19,740 USD",
  days: [
    d("01","Arrival in Entebbe","Gateway to adventure","/assets/15 day trip/15day1.jpg",[s("Arrival & welcome",["Arrive at Entebbe International Airport","Private welcome by your guide","Luxury transfer to Hotel No.5","Relax after your flight"],"ri-plane-line"),s("Accommodation & briefing",["Stay at elegant Hotel No.5","Enjoy premium amenities","Welcome dinner","Private safari briefing"],"ri-hotel-line")],"Elegant arrival","Hotel No.5 offers sophisticated comfort and personal service for a restful first night."),
    d("02–04","Kibale Forest National Park","Kingdom of chimpanzees","/assets/15 day trip/15day4.jpg",[s("Chimpanzee immersion",["Travel to Kibale Forest","Join multi-day chimpanzee treks","See red colobus monkeys and baboons","Take guided forest walks","Enjoy forest sunsets"],"ri-bear-smile-line"),s("Kibale Forest Lodge",["Stay three nights","Comfortable eco-lodge setting","All specified meals","Community encounters","Excellent birding"],"ri-hotel-line")],"Primate capital","Kibale protects 13 primate species and has one of Africa's highest primate densities."),
    d("05–07","Queen Elizabeth National Park","Wildlife & scenery","/assets/15 day trip/15day5.jpg",[s("Wildlife experiences",["Drive or fly to Queen Elizabeth","Track Kyambura's Lost Chimpanzees","Cruise the Kazinga Channel","See hippos, crocodiles and birds","Join morning and evening game drives"],"ri-binoculars-line"),s("Kyambura Gorge Lodge",["Stay three nights","Deluxe accommodation","All specified meals","Private balconies","Sunset views"],"ri-hotel-line")],"Conservation story","The isolated Lost Chimpanzees of Kyambura Gorge are central to a distinctive conservation story."),
    d("08–10","Mgahinga Gorilla National Park","Gorilla trekking in the Virungas","/assets/15 day trip/15day6.jpg",[s("Gorilla encounters",["Travel to Mgahinga","Track mountain gorillas","Spend two full days in the region","Enjoy close wildlife encounters","Receive photography guidance"],"ri-footprint-line"),s("Mount Gahinga Lodge",["Stay three nights","All specified meals","Community experiences","Views of the Virunga volcanoes","Relax between treks"],"ri-hotel-line")],"Profound encounter","Time with mountain gorillas in the Virungas is an emotional wildlife experience few travellers ever forget."),
    d("11","Return to Entebbe","Departure day","/assets/15 day trip/15day2.jpg",[s("Final morning",["Breakfast with mountain views","Pack and say farewell","Transfer to the airstrip","Optional light-aircraft journey"],"ri-sun-line"),s("Entebbe & departure",["Arrive in Entebbe","Optional souvenir shopping","Relax beside Lake Victoria","Transfer to the airport"],"ri-plane-line")],"Departure planning","Evening international flights work best; a day room or extra Entebbe night can be arranged."),
  ],
  highlights: h(["/assets/15 day trip/15day1.jpg","/assets/15 day trip/15day4.jpg","/assets/15 day trip/15day5.jpg","/assets/15 day trip/15day3.jpg","/assets/15 day trip/15day6.jpg","/assets/15 day trip/15day8.jpg","/assets/15 day trip/15day2.jpg","/assets/15 day trip/15day7.jpg"],["Luxury arrival","Kibale rainforest","Chimpanzee immersion","Kyambura Gorge","Virunga gorillas","Premium lodges","Entebbe farewell","Mountain sanctuary"]),
  lodges: [l("Hotel No.5","Entebbe","1 night","Luxury","/assets/luxury-uganda/sheraton-kampala.jpg","A sophisticated and restful start to the journey."),l("Kibale Forest Lodge","Kibale","3 nights","Eco lodge","/assets/luxury-uganda/lux1.png","A comfortable forest base for extended chimpanzee encounters."),l("Kyambura Gorge Lodge","Queen Elizabeth NP","3 nights","Luxury","/assets/luxury-uganda/lux2.png","An elegant lodge overlooking the gorge and savanna."),l("Mount Gahinga Lodge","Mgahinga","3 nights","Luxury","/assets/15 day trip/15day7.jpg","A mountain retreat beneath the Virunga volcanoes.")],
  features: [{icon:"ri-vip-crown-line",title:"Private luxury tour",text:"Exclusive service and premium accommodation"},{icon:"ri-bear-smile-line",title:"Primate focused",text:"Extended chimpanzee and gorilla experiences"},{icon:"ri-calendar-event-line",title:"Flexible dates",text:"Plan dates around your party"},{icon:"ri-settings-3-line",title:"Customizable",text:"Adapt flights, rooms and activities"}], included: ["Ten nights' premium accommodation","Private luxury transport and guide","Multi-day chimpanzee experiences","Kyambura chimpanzee tracking","Mountain gorilla trekking","Kazinga Channel cruise and game drives","Specified meals and park fees","Airport transfers"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Luxury primate safari","USD 19,740 per person"],["Premium accommodation","Included"],["Primate permits","Included"],["Private guiding and transport","Included"]], bookingBenefits: ["Priority primate permits","Dedicated safari planner","Premium room selection","Flexible payment schedule"], pricingInclusions: ["Ten nights' premium accommodation","Private transport and professional guide","All listed primate and wildlife activities","Park fees, permits and specified meals","Airport and internal transfers"], importantNotes: ["Price based on double occupancy","Single supplement: $3,200","Premium upgrades from $500","Uganda visa: USD $50 where applicable",...standardNotes.slice(1)], permitNote,
};

export const uganda14DayLuxury: ItineraryConfig = {
  title: "14-Day Ultimate Uganda Luxury Safari", shortTitle: "14-Day Ultimate Uganda Luxury Safari", eyebrow: "Discover Uganda in unparalleled style & comfort", description: "Uganda's complete luxury circuit: Murchison Falls, Kibale chimpanzees, Queen Elizabeth wildlife, Bwindi gorillas, Lake Bunyonyi, Lake Mburo and the Nile at Jinja.", heroImage: "/assets/14day-luxury/luxury1.png", duration: "14 days", nights: "13 nights", destination: "Uganda", travelStyle: "Luxury", price: "$9,570 USD",
  days: [
    d("01","Arrival: Entebbe to Kampala","Arrival day","/assets/14day-luxury/luxury1.png",[s("Arrival & transfer",["Arrive at Entebbe International Airport","Meet your private driver-guide","Transfer to Sheraton Kampala","Relax after the flight"],"ri-plane-line"),s("Evening in Kampala",["Enjoy the hotel facilities","Optional city introduction","Welcome dinner","Private safari briefing"],"ri-building-line")],"Five-star welcome","Sheraton Kampala provides five-star comfort at the beginning of your Ugandan journey."),
    d("02–03","Murchison Falls National Park","Big game & the Nile","/assets/14day-luxury/luxury2.png",[s("Wildlife & falls",["Morning and evening game drives","Search for lions, elephants and giraffes","Boat to the base of Murchison Falls","Photograph Nile landscapes","Excellent birding"],"ri-binoculars-line"),s("Paraa Safari Lodge",["Stay overlooking the Nile","Fine dining","Sunset cocktails","Optional spa time","Prime park location"],"ri-hotel-line")],"Power of the Nile","Uganda's largest park is home to the Nile's dramatic plunge through a gap only seven metres wide."),
    d("04–05","Kibale Forest National Park","Primate kingdom","/assets/14day-luxury/luxury3.png",[s("Chimpanzees & forest",["Guided chimpanzee tracking","Look for 13 primate species","Take forest nature walks","Exceptional birdwatching","Learn about rainforest ecology"],"ri-bear-smile-line"),s("Chimpundu Lodge",["Luxury forest stay","Guided nature walks","Community experiences","Tea-country views","Fine meals"],"ri-hotel-line")],"Primate capital","Kibale has one of Africa's highest primate concentrations and offers excellent habituated chimpanzee encounters."),
    d("06–07","Queen Elizabeth National Park","Savanna & channel safari","/assets/14day-luxury/luxury4.png",[s("Safari experiences",["Explore the Kasenyi plains","Search for Ishasha's tree-climbing lions","Cruise the Kazinga Channel","See hippos and crocodiles","Identify more than 600 bird species"],"ri-binoculars-line"),s("Mweya Safari Lodge",["Kazinga Channel views","Luxury rooms","Fine dining","Swimming pool","Central park setting"],"ri-hotel-line")],"Wildlife corridor","The Kazinga Channel draws extraordinary concentrations of animals and birds throughout the year."),
    d("08–09","Bwindi Impenetrable Forest","Mountain gorillas","/assets/14day-luxury/luxury5.png",[s("Gorilla trekking",["Enter the UNESCO World Heritage forest","Trek with specialist guides","Find a habituated gorilla family","Spend one hour with the gorillas","Learn about conservation"],"ri-footprint-line"),s("Four Gorillas Lodge",["Forest-side luxury","Spa treatments","Gourmet dining","Community encounters","Peaceful views"],"ri-hotel-line")],"Global sanctuary","Bwindi protects nearly half of the world's mountain gorillas, and every permit supports conservation and local communities."),
    d("10–11","Lake Bunyonyi","Island relaxation","/assets/14day-luxury/luxury6.png",[s("Lake experiences",["Relax after gorilla trekking","Kayak or canoe on the lake","Explore its 29 islands","Take scenic hikes","Visit local communities"],"ri-ship-line"),s("Arcadia Lodge",["Panoramic lake views","Private balconies","Fresh local cuisine","Optional spa treatments","Quiet mountain setting"],"ri-hotel-line")],"Place of many little birds","Lake Bunyonyi's 29 islands and terraced hills create one of Uganda's most peaceful highland landscapes."),
    d("12","Lake Mburo National Park","Walking safari","/assets/14day-luxury/luxury7.png",[s("Savanna adventure",["Guided walking safari","Game drive for zebra, impala and eland","Sunset boat excursion","Birdwatching","Wildlife photography"],"ri-walk-line"),s("Mihingo Lodge",["Luxury rooms among granite rocks","Infinity pool","Fine dining","Stargazing","Views over the savanna"],"ri-hotel-line")],"On foot in the wild","Lake Mburo is one of the few Ugandan parks where guided walking safaris offer close views of plains wildlife."),
    d("13","Jinja & the Source of the Nile","Nile adventure","/assets/14day-luxury/luxury8.png",[s("Source of the Nile",["Visit the historic Nile source","Optional white-water rafting","Optional kayaking","Learn the river's history","Explore Jinja"],"ri-ship-line"),s("Wildwaters Lodge",["Island lodge in the Nile","Luxury tented accommodation","Spa treatments","Fine dining","River views"],"ri-hotel-line")],"Adventure capital","The 6,650-kilometre Nile begins its northward journey here, and Jinja is East Africa's adventure capital."),
    d("14","Return to Kampala & Departure","Journey home","/assets/14day-luxury/luxury1.png",[s("Final morning",["Breakfast beside the Nile","Pack and review photographs","Farewell to the lodge team","Private transfer to Kampala"],"ri-sun-line"),s("Kampala & airport",["Lunch in Kampala","Optional final shopping","Transfer to Entebbe Airport","Check in and farewell"],"ri-plane-line")],"Journey's end","Your guide coordinates the final transfer around your international departure time."),
  ],
  highlights: h([1,2,3,4,5,6,7,8].map(n=>`/assets/14day-luxury/luxury${n}.png`),["Luxury welcome","Murchison Falls","Kibale chimpanzees","Queen Elizabeth","Bwindi gorillas","Lake Bunyonyi","Lake Mburo","Source of the Nile"]),
  lodges: [l("Sheraton Kampala","Kampala","1 night","Luxury","/assets/14day-luxury/sheraton-kampala.jpg","A five-star city welcome."),l("Paraa Safari Lodge","Murchison Falls","2 nights","Luxury","/assets/14day-luxury/paraa-lodge.jpg","A landmark safari lodge overlooking the Nile."),l("Chimpundu Lodge","Kibale","2 nights","Luxury","/assets/14day-luxury/luxury3.png","An upscale forest base for chimpanzee trekking."),l("Mweya Safari Lodge","Queen Elizabeth NP","2 nights","Luxury","/assets/14day-luxury/luxury4.png","An iconic stay above the Kazinga Channel."),l("Four Gorillas Lodge","Bwindi","2 nights","Luxury","/assets/14day-luxury/four-gorillas.png","Forest luxury close to the gorilla trailheads."),l("Arcadia Lodge","Lake Bunyonyi","2 nights","Luxury","/assets/14day-luxury/luxury6.png","A panoramic highland retreat overlooking the islands."),l("Mihingo Lodge","Lake Mburo","1 night","Luxury","/assets/14day-luxury/luxury7.png","A striking lodge built among granite outcrops."),l("Wildwaters Lodge","Jinja","1 night","Luxury","/assets/14day-luxury/wildwaters.jpg","An exclusive island lodge surrounded by the Nile's rapids.")],
  features: [{icon:"ri-vip-crown-line",title:"Ultimate luxury",text:"Uganda's finest lodges and private service"},{icon:"ri-route-line",title:"Complete circuit",text:"Eight signature regions in one journey"},{icon:"ri-settings-3-line",title:"Fully customizable",text:"Adjust pacing, flights and room categories"},{icon:"ri-user-heart-line",title:"Personal service",text:"Private guide throughout the safari"}], included: ["Thirteen nights' luxury accommodation","Private 4x4 and professional guide","Murchison game drives and Nile cruise","Chimpanzee and gorilla permits","Queen Elizabeth game drives and Kazinga cruise","Lake Bunyonyi and Lake Mburo activities","Jinja and Source of the Nile visit","Specified meals, park fees and airport transfers"], excluded: standardExcluded, preparation: standardPreparation,
  pricingRows: [["Ultimate luxury safari","USD 9,570 per person"],["Thirteen nights' accommodation","Included"],["Gorilla permit","Included (USD 700 value)"],["Chimpanzee permit and park fees","Included"],["Private transport and listed activities","Included"]], bookingBenefits: ["Priority permit reservations","Premium lodge selection","Dedicated trip planner","Flexible payment schedule"], pricingInclusions: ["Thirteen nights at listed luxury lodges","Private 4x4 and guide","All listed safaris, cruises and cultural activities","Primate permits and park fees","Specified meals and airport transfers"], importantNotes: ["Price based on double occupancy","Single supplement: $1,000","Premium upgrades from $1,500","Uganda visa: USD $50 where applicable",...standardNotes.slice(1)], permitNote,
};
